services:
  traefik:
    image: traefik:v3.1
    container_name: item-tracker-proxy
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  tracker:
    build: ./backend
    container_name: item-tracker-server
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-item_tracker}
    volumes:
      - ./backend/config:/app/config
    restart: unless-stopped
    init: true
    shm_size: '1gb'
    cap_add:
      - SYS_ADMIN
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tracker.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.tracker.entrypoints=web"
      - "traefik.http.services.tracker.loadbalancer.server.port=3001"

  frontend:
    build: ./frontend
    container_name: item-tracker
    restart: unless-stopped
    depends_on:
      - tracker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.priority=1"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

  db:
    image: postgres:18-alpine
    container_name: item-tracker-db
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME:-item_tracker}
    volumes:
      - item_tracker_db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"
    restart: unless-stopped

volumes:
  item_tracker_db_data:
